CREATE TABLE `report_base_info` (
  `id` bigint(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_name` varchar(100) NOT NULL DEFAULT '' COMMENT '填表人',
  `branch_name` varchar(200) NOT NULL DEFAULT '' COMMENT '网点名称',
  `onwer_name` varchar(100) NOT NULL DEFAULT '' COMMENT '网点负责人',
  `onwer_phone` varchar(100) NOT NULL DEFAULT '' COMMENT '网点负责人电话',
  `add_time` datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '反馈时间',
  `base_title_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '报表项目title表',
  `item1` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item2` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item3` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item4` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item5` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item6` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item7` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item8` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item9` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item10` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item11` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item12` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item13` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item14` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item15` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item16` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item17` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item18` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item19` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  `item20` varchar(400) NOT NULL DEFAULT '' COMMENT '表单项1',
  PRIMARY KEY (`id`),
  KEY `idx_branch_name` (`branch_name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='报表基础信息表';

